### ISSUE TITLE
Reproducible Builds

### ISSUE THREAD

**Issue by IzzySoft** [zelenyhleb/tortoise#40]
I've checked your app if its build is reproducible (see: [Reproducible bulds, special client support and more in our repo](https://android.izzysoft.de/articles/named/iod-rbs-mirrors-clients)) – it principally is, but always requires manual adjustments to the recipe:

* with v0.5.1, you first built the APK and then committed your last changes – so your APK has the previous commit hash embedded and not the one the tag points to
* with v0.5.2 it looks the same – just that the commit cannot even be found in the repo here (you probably build from some private branch I guess?)

We'd appreciate if you could help keeping your build reproducible. We've prepared some [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) for that. Please take a look at least at its first and most crucial item, which we call "The first basic rule" or "§1":

> **§1: Always build the APK from exactly the commit your release-tag will point to!**

If for v0.5.2 you could at least push the missing commit (96d8c9cbd427bac6e85cac0fd42679c17ada4742) I could retry the build tomorrow to bring back the "green shield" to [your app at IzzyOnDroid](https://apt.izzysoft.de/packages/ru.krivocraft.tortoise).

Looking forward to your reply!

PS: Be welcome to [pick a badge](https://gitlab.com/IzzyOnDroid/repo/#if-my-app-is-available-here-do-you-have-a-badge-i-can-use-to-link-to-it) to link to your app there, e.g. from your Readme. Next to the usual badges, there are also "shield.io shields" available if those fit you better :wink:

**Comment by zelenyhleb** [comment]
Hi @IzzySoft.
Just checked out releases page and the latest release points to this commit: https://github.com/zelenyhleb/tortoise/commit/e8d00c569e14f797c2f2915e9fe3e3682d8e8013

Your hash does not match with mine, but somehow points to "dangling" commit. How did you acquire that hash?

Regarding your badges suggestion, thank you, maybe once I'll place one...

**Comment by IzzySoft** [comment]
> How did you acquire that hash?

It's embedded in your APK, see `META-INF/version-control-info.textproto`.

> Regarding your badges suggestion, thank you, maybe once I'll place one...

Thanks!

**Comment by obfusk** [comment]
> Your hash does not match with mine, but somehow points to "dangling" commit. How did you acquire that hash?

This would happen e.g. if you build the APK (embedding the current commit hash) and then rebase/squash/amend before tagging (resulting in the tag having a different commit hash). As the old commit hash is embedded in the APK, it cannot be reproduced by building from the tag, especially if the commit it's not even part of the repository.

And indeed, if we look at https://github.com/zelenyhleb/tortoise/pull/39, we see the original commit hash in the PR is 96d8c9c (so presumaby the APK was built from that branch, before the PR was merged into master) but the commit merged into master (and tagged as v0.5.2) is e8d00c5.

**Comment by IzzySoft** [comment]
@zelenyhleb v0.5.2 is now marked "RB failed" here as we cannot fix it. May I recommend taking a look at our [hints on reproducible builds](https://gitlab.com/IzzyOnDroid/repo/-/wikis/Reproducible-Builds) and, for the next releases, keep the "golden rule" aka "first basic rule" in mind? I'm pretty sure, with that v0.5.3 (or whichever version follows) will be RB again. Thanks a lot in advance!

**Comment by zelenyhleb** [comment]
@obfusk @IzzySoft thank you for detailed explanation. 
Is it true that to keep RB green, I just need to re-publish 0.5.2 version built from master branch?

**Comment by IzzySoft** [comment]
> Is it true that to keep RB green, I just need to re-publish 0.5.2 version built from master branch?

No, that tag has been processed now and would not be re-processed (the download remains available, though); apart from that, it's not good practice to replace what has already been distributed (here especially the APK). We'd check again with the next release, which then (hopefully) has it green again.

**Comment by zelenyhleb** [comment]
Ok, so before the next release (which has no ETA yet) the issue became irrelevant. 
Thank you for your explanations again, I'll keep them in mind when publishing the v0.5.3.

**Comment by IzzySoft** [comment]
If you want a check right before the next release, just attach an APK here (*rename* it to `*.zip` so you can attach it, do not put it inside another ZIP please) and name the commit it was built from; I'd then check if it's RB (and if not try to find out what might be wrong). That way we do not "hang" again with a release we cannot confirm RB.

**Comment by IzzySoft** [comment]
@zelenyhleb any ETA here? Just asking for orientation, as it looks rather "silent" here…

**Comment by zelenyhleb** [comment]
Hi @IzzySoft
Next release is not planned yet. Any information about future releases can be tracked via issues/milestones.
So, no ETA here so far

**Comment by IzzySoft** [comment]
OK, thanks! Won't be able to track via milestones, so I hope to receive a ping here. Or the next update simply passes, who knows…
